apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: calc-serverless
spec:
  template:
    spec:
      containers:
        # Mettre nom de l'image docker à utiliser
        - image: docker.io/lenorenaud/calculator-interface:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80